packages:

  - name: bash
    origin: LEI/dot-bash

  - name: git
    origin: LEI/dot-git

  - name: termux
    os: ["android"]
    origin: LEI/dot-termux

  - name: tmux
    origin: LEI/dot-tmux

  - name: vim
    origin: LEI/dot-vim
