---

roles:
  - name: bash
    url: "https://github.com/LEI/dot-bash"

  - name: gpg
    url: "https://github.com/LEI/dot-gpg"

  - name: git
    url: "https://github.com/LEI/dot-git"
    dependencies: ["gpg"]

  - name: vim
    url: "https://github.com/LEI/dot-vim"
    dependencies: ["bash", "git"]

  - name: tmux
    url: "https://github.com/LEI/dot-tmux"
    dependencies: ["git"]

  - name: termux
    url: "https://github.com/LEI/dot-termux"
    os: ["android"]

  - name: arch
    url: "https://github.com/LEI/dot-arch"
    os: ["arch"]

  - name: osx
    url: "https://github.com/LEI/dot-osx"
    os: ["darwin"]

  - name: hammerspoon
    url: "https://github.com/LEI/dot-hammerspoon"
    os: ["darwin"]

  - name: i3
    url: "https://github.com/LEI/dot-i3"
    os: ["arch"]
    dependencies: ["arch"]

  - name: rxvt
    url: "https://github.com/LEI/dot-rxvt"
    os: ["arch"]
    dependencies: ["i3"]

  - name: mutt
    url: "https://github.com/LEI/dot-mutt"
    os: ["darwin"]
    dependencies: ["gpg"]

  - name: usql
    url: "https://github.com/LEI/dot-usql"
    os: ["darwin"]

  - name: micro
    url: "https://github.com/LEI/dot-micro"
    os: ["darwin"]

  - name: htop
    url: "https://github.com/LEI/dot-htop"

  - name: node
    url: "https://github.com/LEI/dot-node"

  - name: php
    url: "https://github.com/LEI/dot-php"

  - name: python
    url: "https://github.com/LEI/dot-python"

  - name: ruby
    url: "https://github.com/LEI/dot-ruby"

  - name: rust
    url: "https://github.com/LEI/dot-rust"
    os: ["!alpine", "!darwin"]
