---

roles:
  - name: bash
    url: "https://github.com/LEI/dot-bash"

  - name: git
    url: "https://github.com/LEI/dot-git"

  - name: vim
    url: "https://github.com/LEI/dot-vim"
    dependencies: ["bash", "git"]

  - name: tmux
    url: "https://github.com/LEI/dot-tmux"
    dependencies: ["git"]

  - name: termux
    url: "https://github.com/LEI/dot-termux"
    os: ["android"]

  - name: osx
    url: "https://github.com/LEI/dot-osx"
    os: ["darwin16"] # Sierra

  - name: hammerspoon
    url: "https://github.com/LEI/dot-hammerspoon"
    os: ["darwin"]

  - name: i3
    url: "https://github.com/LEI/dot-i3"
    os: ["arch"]

  - name: rxvt
    url: "https://github.com/LEI/dot-rxvt"
    os: ["arch"]
    dependencies: ["i3"]

  - name: usql
    url: "https://github.com/LEI/dot-usql"
    os: ["darwin"]
