roles:

  - name: bash
    origin: LEI/dot-bash

  - name: git
    origin: LEI/dot-git

  - name: tmux
    origin: LEI/dot-tmux

  - name: vim
    origin: LEI/dot-vim

  - name: termux
    origin: LEI/dot-termux
    os: ["android"]

  - name: osx
    origin: LEI/dot-osx
    os: ["darwin16"] # Sierra

  - name: hammerspoon
    origin: LEI/dot-hammerspoon
    os: ["darwin"]
    # target: /tmp/osx
    # package:
    #   dirs:
    #     - .config
    #   links:
    #     - .hammerspoon/*.lua
