target: /tmp/dot
roles:

  - name: bash
    source: LEI/dot-bash

  - name: git
    source: LEI/dot-git

  - name: tmux
    source: LEI/dot-tmux

  - name: vim
    source: LEI/dot-vim

  - name: termux
    source: LEI/dot-termux
    os: ["android"]

  # El Capitan: darwin15.6.0
  - name: osx
    source: LEI/dot-osx
    os: ["darwin16"]

  - name: hammerspoon
    source: LEI/dot-hammerspoon
    # target: /tmp/osx
    dir: .hammerspoon
    link: .hammerspoon/*
  # - name: hammerspoon
  #   source: LEI/dot-hammerspoon
  #   os: ["darwin"]
