---
git:
  host: github.com
  # user: LEI
  # scheme: https

roles:
  - "bash:LEI/dot-bash"

  - name: node
    url: LEI/dot-node
    os: ["!android"]

  - name: php
    url: LEI/dot-php
    os: ["!android"]

  - name: python
    url: LEI/dot-python

  - name: ruby
    url: LEI/dot-ruby

  # - name: rust
  #   url: LEI/dot-rust
  #   os: ["!alpine", "!android"]

  - name: termux
    url: LEI/dot-termux
    os: ["android"]

  - name: arch
    url: LEI/dot-arch
    os: ["arch"]

  - name: osx
    url: LEI/dot-osx
    os: ["darwin"]

  - name: hammerspoon
    url: LEI/dot-hammerspoon
    os: ["darwin"]

  - name: gpg
    url: LEI/dot-gpg

  - name: git
    url: LEI/dot-git
    dependencies: ["gpg"]

  - name: vim
    url: LEI/dot-vim
    dependencies: ["bash", "git"]

  - name: tmux
    url: LEI/dot-tmux
    dependencies: ["git"]

  - name: i3
    url: LEI/dot-i3
    os: ["arch"]
    dependencies: ["arch"]

  - name: rxvt
    url: LEI/dot-rxvt
    os: ["arch"]
    dependencies: ["i3"]

  - name: mutt
    url: LEI/dot-mutt
    os: ["darwin"]
    dependencies: ["gpg"]

  - name: htop
    url: LEI/dot-htop

  - name: usql
    url: LEI/dot-usql
    os: ["darwin"]
