# https://goreleaser.com
builds:
- env:
    - CGO_ENABLED=0
  # main: main.go
  # binary: dot # "{{ .ProjectName }}"
  goos: # https://golang.org/doc/install/source#environment
    - windows
    - darwin
    - linux
    # - freebsd
  goarch:
    - 386
    - amd64
  #   - arm
  #   - arm64
  # goarm:
  #   - 6
  #   - 7
archive:
  # format: binary # tar.gz (default), zip
  name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  # replacements:
  #   darwin: Darwin
  #   linux: Linux
  #   windows: Windows
  #   386: i386
  #   amd64: x86_64
  # files: []
  # hooks: {}
# sign:
#    artifacts: checksum
checksum:
  # name_template: "checksums.txt"
  # name_template: "{{ .Binary }}-checksum.txt"
  name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}-checksums.txt"
snapshot:
  # Default is "SNAPSHOT-{{.Commit}}"
  name_template: "{{ .Tag }}-next"
changelog:
  # sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
git:
  short_hash: true
brew:
  name: dot
  github:
    owner: LEI
    name: homebrew-dot
  # download_strategy:
  # commit_author:
  #   name:
  #   email:
  # folder: Formula
  # caveats: ""
  homepage: "https://github.com/LEI/dot"
  # description: ""
  dependencies:
    - git
    # - bash
  # conflicts: []
  # plist: |
  # test: |
  # install (default: bin.install "program"°
