# https://goreleaser.com
builds:
- env:
    - CGO_ENABLED=0
  # main: main.go
  # binary: dot
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - 386
    - amd64
archive:
  # format: tar.gz
  # replacements:
  #   darwin: Darwin
  #   linux: Linux
  #   windows: Windows
  #   386: i386
  #   amd64: x86_64
  # files:
  #   - ...
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
git:
  short_hash: true
brew:
  # name: dot
  # github:
  #   owner: LEI
  #   name: homebrew-tap
  # download_strategy:
  # commit_author:
  #   name:
  #   email:
  # folder: Formula
  # caveats: ""
  homepage: "https://github.com/LEI/dot"
  # description: ""
  dependencies:
    - git
    # - bash
  # conflicts: []
  # plist: |
  # test: |
  # install (default: bin.install "program"°
