sudo: required

language: bash

services:
  - docker

before_install:
  - docker build -t lei/dot .
  - docker run -d --name dot lei/dot -c "dot -R $DOT"
  - docker ps -a
  - docker run lei/dot -c "ls -la"

script:
  - ls -lah
