sudo: required

services:
  - docker

language: bash

# addons:
#   apt:
#     sources:
#       - debian-sid
#     packages:
#       - shellcheck

install:
  # - shellcheck ./bin/* ./lib/*.bash ./src/**/.dotsh
  - docker-compose build

script:
  - docker-compose run test
  - ls -la bin
  - PATH="$PATH:$HOME/bin"
  - echo $PATH | tr -s ':' '\n'
  - which dot
  - ./bin/dot -R .

notifications:
  email: false
