sudo: required

language: go

os:
  - linux
  # - osx

# services:
#   - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y curl # vim tmux

install:
  # - golint
  - go vet
  - go get github.com/LEI/dot
  - go install
  # - docker-compose build

script:
  # - "for t in tests/docker-compose.*.yml; do docker-compose -f docker-compose.yml -f $t run test; done"
  # - docker-compose run test
  - yes | dot sync --https -d
  - tmux new-session -n test "vim +PlugInstall +qall; exit"
  - test -d $HOME/.tmux/plugins/tpm
  - tree ~/.vim || ls -la ~/.vim
  - test -d $HOME/.vim/plugged

notifications:
  email: false
