sudo: required

language: go

os:
  - linux
  # - osx

# services:
#   - docker

install:
  # - docker-compose build
  # - golint
  - go vet
  - go get github.com/LEI/dot
  - go install

script:
  # - "for t in tests/docker-compose.*.yml; do docker-compose -f docker-compose.yml -f $t run test; done"
  # - docker-compose run test
  # - PATH="$PATH:$HOME/bin"
  # - echo $PATH | tr -s ':' '\n'
  - dot
  - test -d $HOME/.dot

notifications:
  email: false
