sudo: required

services:
  - docker

language: bash

install:
  - docker-compose build

script:
  - docker-compose run test
  - docker-compose -f docker-compose.yml -f tests/docker-compose.bash.yml run test
  - docker-compose -f docker-compose.yml -f tests/docker-compose.tmux.yml run test
  - docker-compose -f docker-compose.yml -f tests/docker-compose.vim.yml run test
  # - PATH="$PATH:$HOME/bin"
  # - echo $PATH | tr -s ':' '\n'
  # - go install
  # - dot -s $DOT/src/tmux
  # - cd
  # - ls -lah

notifications:
  email: false
