sudo: required

services:
  - docker

language: bash

addons:
  apt:
    # sources:
    #   - debian-sid
    packages:
      - shellcheck

install:
  - shellcheck ./bin/dot
  - shellcheck ./bin/*
  - docker-compose build

script:
  - docker-compose run test

notifications:
  email: false
