# sudo: required
# #group: deprecated-2017Q2

language: go

# go:
#   - master

os:
  - linux
  # - osx # brew install docker-compose

services:
  - docker

# cache:
#   directories:
#     - $GOPATH/src
#     - $GOPATH/pkg

stages:
  - compile
  - test
  - name: deploy
    if: branch = latest

jobs:
  include:
    - stage: compile
      before_script:
        # - sudo apt-get -qq update
        # - sudo apt-get install -y vim tmux
        - go get github.com/sirupsen/logrus
        - go get github.com/spf13/cobra
        - go get github.com/spf13/viper
        # - go get github.com/mattn/goveralls
      script:
        # - golint
        - go vet ./...
        - go test -v ./... # -covermode=count -coverprofile=coverage.out
        # - go install
        # - yes | dot --https
        # # - curl -sfLo ~/.vim/autoload/plug.vim --create-dirs 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
        # - tmux new-session -n test "vim -E -s -u $HOME/.vim/vimrc +PlugInstall +qall; exit"
        # - test -d $HOME/.tmux/plugins/tpm
        # - test -d $HOME/.vim/plugged
        # - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
    - stage: test
      before_script:
        - docker-compose build
      script:
        # - "for t in tests/docker-compose.*.yml; do docker-compose -f docker-compose.yml -f $t run test; done"
        - docker-compose run test
    - stage: deploy
      before_deploy:
        - mkdir -p bin
        - GOOS=darwin  GOARCH=amd64 go build -o bin/dot-darwin-amd64
        - GOOS=linux   GOARCH=amd64 go build -o bin/dot-linux-amd64
        - GOOS=windows GOARCH=amd64 go build -o bin/dot-windows-amd64.exe
      deploy:
        provider: releases
        api_key:
          secure: oY3u9O1FkqsozEtRY0Jn4/4+2EP6UNCcpI2+j0uIFMzybnGl7RyvYizWGSElbzIALQySSFMv39g69BCiPCZmeilcfiZs1C9qXP13RC21/XfHSpmLiyD0Va1TuADC6BklbfQ/XDpFUrTAY/ErFybLjKkYbfI6ntInZkKq7qaak5OpIBGe0aFNWtidHEnu24yK0jcUIui/qMioBwY5El9F9qcwvdMYVU9g4o32uKYrTcHaNRG2pcTEtZmMNsojYpyE+2S1y9Q55Gz/AyU0C+wBgj+NHeWpLSfac6x/I8vxlsUmV2QozJhct4ws3RJ5rscy73DVdNYEdO1whka3CUvUWIw1m7SReaKqWUl4NpOvaNfH5cQO/0kgZLjrTq5WLyiPpUTqMVA5MHzKVN9351MV2i8hhXrK+8H0/ihNnLSl6RbcgIDbp3I7P59YmofuT7+Iy1tiBmmHvBJDuU1DcwHQYqKnSpVVkuOIgt6bqvhdKCCTV48VFW+0+gh3M428At/U6Nl56XUJ0YG55CFGLd03vIp7n1rUnyv9/uNMY3b0aDpAj4trfhUybDGwoRG5Pb0FnFQVh/jRtImsB0IWW823yU6b+1GjbF0a5SfWDCRAaTE6QQukpWdSQdjyhmImbsdpAKbi497oDM3KraM9R77WQfY/JSD01Dzj+KDvX7lP60Y=
        file: bin/*
        # skip_cleanup: true
        on:
          repo: LEI/dot
          # tags: true

notifications:
  email: false
