sudo: required
#group: deprecated-2017Q2

language: go

# go:
#   - master

os:
  - linux
  # - osx # brew install docker-compose

services:
  - docker

before_install:
  - sudo apt-get -qq update
  # - sudo apt-get install -y vim tmux

install:
  # - golint
  # - go vet
  # - go get github.com/LEI/dot
  # - go install
  - docker-compose build

script:
  # - "for t in tests/docker-compose.*.yml; do docker-compose -f docker-compose.yml -f $t run test; done"
  - docker-compose run test
  # - yes | dot --https
  # # - curl -sfLo ~/.vim/autoload/plug.vim --create-dirs 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  # - tmux new-session -n test "vim -E -s -u $HOME/.vim/vimrc +PlugInstall +qall; exit"
  # - test -d $HOME/.tmux/plugins/tpm
  # - test -d $HOME/.vim/plugged

notifications:
  email: false
