sudo: required

services:
  - docker

language: bash

install:
  - docker-compose build

script:
  - "for t in tests/docker-compose.*.yml; do docker-compose -f docker-compose.yml -f $t run test; done"
  - docker-compose run test_all
  # - PATH="$PATH:$HOME/bin"
  # - echo $PATH | tr -s ':' '\n'
  # - go install
  # - dot -s $DOT/src/tmux
  # - cd
  # - ls -lah

notifications:
  email: false
