sudo: required

services:
  - docker

language: bash

before_install:
  - docker-compose build
  - docker-compose run test
  # - docker-compose up -d # ps
  # - docker run lei/dot -c "ls -la"

script:
  - ls -lah
  - docker ps -a
  - docker-compose ps

notifications:
  email: false
