sudo: false

language: go

os:
  - linux

services:
  - docker

# cache:
#   directories:
#     - $GOPATH/src
#     - $GOPATH/pkg

stages:
  - build
  - test
  - name: deploy
    on:
      repo: LEI/dot
      tags: true
      condition: $TRAVIS_OS_NAME = linux
  # - name: deploy
  #   # if: branch = master

install:
  - scripts/test.sh

jobs:
  include:

    - stage: build
      install: true
      before_script: docker-compose build test
      script: docker-compose run test
      # "for t in tests/docker-compose.*.yml; do docker-compose -f docker-compose.yml -f $t run test; done"

    - stage: test
      install: scripts/release.sh --snapshot
      before_script: docker-compose build test_os
      script: docker-compose run test_os
      env: OS=alpine

    - stage: test
      install: scripts/release.sh --snapshot
      before_script: docker-compose build test_os
      script: docker-compose run test_os
      env: OS=archlinux

    - stage: test
      install: scripts/release.sh --snapshot
      before_script: docker-compose build test_os
      script: docker-compose run test_os
      env: OS=centos

    - stage: test
      install: scripts/release.sh --snapshot
      before_script: docker-compose build test_os
      script: docker-compose run test_os
      env: OS=debian

    - stage: test
      install:
        # - (cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update)
        - export HOMEBREW_NO_ANALYTICS=1
        - export HOMEBREW_NO_EMOJI=1
        - brew upgrade --quiet || true
        - brew install --quiet gnu-sed --with-default-names
        - if test ! -d $GOPATH/bin; then mkdir $GOPATH/bin; fi
        - scripts/release.sh --snapshot
      before_script: cp dist/darwin_amd64/dot /usr/local/bin/dot
      script: scripts/e2e-test.sh
      env: OS=darwin
      os: osx
      language: go

    - stage: deploy
      addons:
        apt:
          packages:
          - rpm
          - snapd
      env:
        - PATH=/snap/bin:$PATH
      before_deploy:
        - sudo snap install snapcraft --classic
        # - mkdir -p dist
        # - GOOS=darwin  GOARCH=amd64 go build -o dist/dot-darwin-amd64
        # - GOOS=linux   GOARCH=amd64 go build -o dist/dot-linux-amd64
        # - go get github.com/inconshreveable/mousetrap
        # - GOOS=windows GOARCH=amd64 go build -o dist/dot-windows-amd64.exe
      # after_success:
      #   # docker login is required if you want to push docker images.
      #   # DOCKER_PASSWORD should be a secret in your .travis.yml configuration.
      #   - test -n "$TRAVIS_TAG" && docker login -u=myuser -p="$DOCKER_PASSWORD"
      deploy:
        provider: script
        # Build into dist and release go program
        script: echo curl -sL https://git.io/goreleaser # | bash # scripts/release.sh
        # provider: releases
        # api_key:
        #   secure: "$DEPLOY_API_KEY"
        # # prerelease: true
        # # draft: true
        # file: dist/*
        # file_glob: true
        skip_cleanup: true
        # on:
        #   repo: LEI/dot
        #   tags: true
        #   condition: $TRAVIS_OS_NAME = linux

notifications:
  email: false
