sudo: required

services:
  - docker

language: bash

install:
  # - golint
  - go vet
  - go install
  - echo $PATH
  - echo $GOPATH
  # - docker-compose build

script:
  # - "for t in tests/docker-compose.*.yml; do docker-compose -f docker-compose.yml -f $t run test; done"
  # - docker-compose run test
  # - PATH="$PATH:$HOME/bin"
  # - echo $PATH | tr -s ':' '\n'
  - pwd
  - ls -lah
  - dot -h
  - cd
  - ls -lah

notifications:
  email: false
