# sudo: required

# services:
#   - docker

language: bash

addons:
  apt:
    # sources:
    #   - debian-sid
    packages:
      - shellcheck

install:
  - shellcheck ./bin/*
  - shellcheck ./lib/*.bash
  - shellcheck ./src/**/.dotsh
  # - docker-compose build

script:
  # - docker-compose run test
  - echo $PATH
  - ./bin/dot -R .

notifications:
  email: false
