sudo: false

services:
  - docker

language: go

# go:
#   - "1.x"
#   - "1.8"
#   - "1.10.x"
#   - master

os:
  - linux

matrix:
  allow_failures:
    - go: master
  fast_finish: true

# cache:
#   directories:
#     # - $GOPATH/bin
#     # - $GOPATH/pkg/dep
#     # - $GOPATH/src/github.com/LEI/dot/dist
#     - $GOPATH/src/github.com/LEI/dot/vendor

branches:
  only:
  - master

# https://github.com/travis-ci/travis-ci/issues/5032
before_install:
  - if echo "$TRAVIS_COMMIT_MESSAGE" | grep -F -q "[skip travis]"; then exit 0; fi

stages:
  - build
  - test
  - deploy

# go run build.go vendor
install: make vendor

script: make check

# make: go run build.go vendor check install

jobs:
  include:

    - stage: build
      # install: skip
      script:
        # - make build && du -sh dist/*_*/*
        - make install
        - dot --help
        # - dot --release
        - dot --version

    - &base
      stage: test
      # This stage builds from source
      # if: tag IS present # FIXME if: env(OS) != ""
      # go run build.go -v vendor docker
      script: make docker
      skip_cleanup: true
      # env: OS=debian

    - <<: *base
      env: OS=alpine

    - <<: *base
      env: OS=archlinux

    - <<: *base
      env: OS=centos

    - <<: *base
      env: OS=debian

    - stage: test
      # if: tag IS present
      script:
        - brew --version
        # - (cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update)
        # - brew update --quiet
        # - brew upgrade --quiet # || true
        - brew install --quiet gnu-sed --with-default-names
        - export HOMEBREW_NO_ANALYTICS=1
        - export HOMEBREW_NO_AUTO_UPDATE=1
        - export HOMEBREW_NO_EMOJI=1
        - if test ! -d $GOPATH/bin; then mkdir $GOPATH/bin; fi
        - make # go run build.go vendor check install
          # - go run build.go build:darwin
        # - cp dist/darwin_amd64/dot /usr/local/bin/dot
        - curl -sSL https://git.io/dotfiles.config -o $HOME/.dotrc.yml
        - scripts/e2e-test.sh
      env: OS=darwin
      os: osx
      language: go

    - stage: deploy
      addons:
        apt:
          packages:
            # Goreleaser nfpm and snap pipes
            - rpm
            - snapd
            # Graphviz dot format for deps.png
            - graphviz
      env:
        # Needed for the snap pipe
        - PATH=/snap/bin:$PATH
      before_deploy:
        # Needed for the snap pipe
        - sudo snap install snapcraft --classic
        # Build docs for Github pages
        - scripts/build-docs.sh
      deploy:

        # Publish Github pages and coverage status
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          local-dir: docs
          target-branch: gh-pages
          keep-history: true
          fqdn: dot.lei.sh
          # email: deploy@travis-ci.org
          # name: Deployment Bot
          committer-from-gh: true
          # verbose: true
          on:
            repo: LEI/dot
            branch: master
            condition: $TRAVIS_OS_NAME = linux

        # Release with goreleaser when a tag is specified
        # https://goreleaser.com/ci/
        - provider: script
          # if: tag IS present
          # script: curl -sL https://git.io/goreleaser | bash
          # script: go run build.go vendor -only release
          script: make release
          skip_cleanup: true
          on:
            repo: LEI/dot
            branch: docs
            tags: true
            condition: $TRAVIS_OS_NAME = linux

      after_success:
        - make coverage # go run build.go coverage
        - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
