sudo: required

services:
  - docker

language: bash

before_install:
  - docker-compose build
  - docker-compose up -d
  - docker-compose ps
  # - docker-compose run test
  # - docker run lei/dot -c "ls -la"

# script:
#   - ls -lah

notifications:
  email: false
