sudo: required

services:
  - docker

language: bash

install:
  - docker-compose build

script:
  - docker-compose run test
  # - PATH="$PATH:$HOME/bin"
  # - echo $PATH | tr -s ':' '\n'
  # - go install
  # - dot -s $DOT/src/tmux
  - cd
  - ls -lah

notifications:
  email: false
