# https://github.com/gohugoio/hugo/blob/master/appveyor.yml
# https://github.com/joefitzgerald/go-plus/blob/master/appveyor.yml<Paste>
# https://blog.markvincze.com/setting-up-an-appveyor-pipeline-for-golang/

image: Visual Studio 2017

# version: 1.0.0.{build}

platform: x64

branches:
  only:
    - master

init:
  # - set PATH=%PATH:C:\MinGW\bin;=%
  # - C:\msys64\usr\bin\sh.exe --login /c/projects/dot/scripts/setup-win.sh
  - set PATH=%PATH%;C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin;%GOPATH%\bin
  - go version
  - go env

environment:
  # CGO_ENABLED: 0 # Required (1) for go test -race
  GOPATH: C:\GOPATH\
  # DOT_BUILD_TAGS:
  # OS: windows

# clones and cd's to path
clone_folder: C:\GOPATH\src\github.com\LEI\dot

install:
  # - gem install asciidoctor
  # - pip install docutils
  # - go get ...

build_script:
  - go run build.go vendor check install # testRace
  # - echo %USERPROFILE%
  - touch C:\Users\appveyor\.dotnc
  # - mv C:\projects\dot\.dotrc.yml C:\Users\appveyor\.dotrc.yml
  - dot --version
  - dot ls
  - dot sync --verbose
  - dot install --packages --verbose
  - go run build.go windows
  # - choco install --yes --no-progress docker-compose
  # - OS=windows go run build.go -v docker
  # - docker-compose build test_os
  # - docker-compose up test_os

# artifacts:
#   - path: .\dist\windows_amd64\dot
#     name: "Dot Windows binary"
