# https://github.com/gohugoio/hugo/blob/master/appveyor.yml

# image: Visual Studio 2015

init:
  - set PATH=%PATH%;C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin;%GOPATH%\bin
  - go version
  - go env

environment:
  # CGO_ENABLED: 0 # Required (1) for go test -race
  GOPATH: C:\GOPATH\
  # DOT_BUILD_TAGS:

# clones and cd's to path
clone_folder: C:\GOPATH\src\github.com\LEI\dot

install:
  # - gem install asciidoctor
  # - pip install docutils
  - go get github.com/magefile/mage

build_script:
  - mage vendor # testRace
  - mage -v check
  - mage install
  # - hugo -s docs/
  # - hugo --renderToMemory -s docs/
  - dot --version
  # - dot ls
  - choco install docker-compose
  - OS=windows mage -v docker
