# https://github.com/gohugoio/hugo/blob/master/appveyor.yml

image: Visual Studio 2017

branches:
  only:
    - master

init:
  # - set PATH=%PATH:C:\MinGW\bin;=%
  # - C:\msys64\usr\bin\sh.exe --login /c/projects/dot/scripts/setup-win.sh
  - set PATH=%PATH%;C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin;%GOPATH%\bin
  - go version
  - go env

environment:
  # CGO_ENABLED: 0 # Required (1) for go test -race
  GOPATH: C:\GOPATH\
  # DOT_BUILD_TAGS:
  # OS: windows

# clones and cd's to path
clone_folder: C:\GOPATH\src\github.com\LEI\dot

install:
  # - gem install asciidoctor
  # - pip install docutils
  - go get github.com/magefile/mage

build_script:
  - mage vendor # testRace
  - mage -v check
  - mage install
  - echo %USERPROFILE% # - $null > C:\home\.dotnc
  - dot --version
  - dot ls
  - dot sync --verbose
  - dot install --verbose # --packages
  - mage windows
  # - choco install --yes --no-progress docker-compose
  # - OS=windows mage -v docker
  # - docker-compose build test_os
  # - docker-compose up test_os

# artifacts:
#   - path: .\dist\windows_amd64\dot
#     name: "Dot Windows binary"
