# https://github.com/gohugoio/hugo/blob/master/appveyor.yml

# image: Visual Studio 2017

init:
  - set PATH=%PATH%;C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin;%GOPATH%\bin
  - go version
  - go env

environment:
  # CGO_ENABLED: 0 # Required (1) for go test -race
  GOPATH: C:\GOPATH\
  # DOT_BUILD_TAGS:
  # OS: windows

# clones and cd's to path
clone_folder: C:\GOPATH\src\github.com\LEI\dot

install:
  # - DryRun: --noop / --what-if
  - choco install --yes --no-progress docker-compose
  # - gem install asciidoctor
  # - pip install docutils
  - go get github.com/magefile/mage

build_script:
  - mage vendor # testRace
  - mage -v check
  - mage install
  - dot --version
  - dot ls
  - dot install --packages --verbose
  - mage windows
  # - OS=windows mage -v docker
  # - docker-compose build test_os
  # - docker-compose up test_os

# artifacts:
#   - path: .\dist\windows_amd64\dot
#     name: "Dot Windows binary"
