version: "2"

services:

  dot:
    image: lei/dot
    depends_on:
      - image
    entrypoint: /bin/bash
    command: -l -c '/go/bin/dot -s $$DOT/src/tmux && tmux new-session; bash -l'
    # command: -l -c '/go/bin/dot -s $$DOT/src/tmux; tmux new-session "vim +PlugInstall +qall; exit"; bash -l'

  test:
    image: lei/dot
    depends_on:
      - image
    environment:
      GIT_USER_NAME: Docker Test
      GIT_USER_USERNAME: docker
      GIT_USER_EMAIL: docker@test.io
    entrypoint: /bin/bash
    command: |
      -l -c '
      bashrc=$$(tail -n1 ~/.bashrc);
      /go/bin/dot -s $$DOT/src/tmux
      echo BRC $$bashrc
      echo BRC $$(tail -n1 ~/.bashrc)
      if [[ "$$bashrc" == "$$(tail -n1 ~/.bashrc)" ]]; then echo ~/.bashrc was not modified; exit 1; fi;
      tmux new-session -n test "exit";
      test -d "$$HOME/.tmux/plugins/tpm"'

  image:
    build: .
    image: lei/dot
    container_name: dot
