version: "2"

services:

  dotimg:
    build: .
    image: lei/dot
    container_name: dot
    # entrypoint: /bin/bash
    environment:
      GIT_AUTHOR_NAME: Docker
      GIT_AUTHOR_EMAIL: do@ck.er
    command: |
      -l -c '
      # run dot --https;
      # run tmux -2 -u new-session -n test "vim -E -s -u $$HOME/.vimrc +PlugInstall +qall; exit";
      exec bash -l;'
    # command: -l -c 'dot -p tmux=LEI/dot-tmux -p vim=LEI/dot-vim; tmux new-session "vim +PlugInstall +qall; exit"; bash -l'

  test:
    image: lei/dot
    depends_on:
      - dotimg
    container_name: dot_test
    # entrypoint: /bin/bash
    command: -l -c '$$DOT/test.sh'
