version: "2"

services:

  image:
    build: .
    image: lei/dot
    container_name: dot

  dot:
    image: lei/dot
    depends_on:
      - image
    # entrypoint: /bin/bash
    command: -l -c 'dot -s $$DOT; bash -l'
    # command: -l -c 'dot -p tmux=LEI/dot-tmux -p vim=LEI/dot-vim; tmux new-session "vim +PlugInstall +qall; exit"; bash -l'

  test:
    image: lei/dot
    depends_on:
      - image
    # entrypoint: /bin/bash
    command: |
      -l -c 'run() { printf "%s\n" "TEST: $$*"; "$$@" || exit 1; }
      tail_bashrc="$$(tail -n1 ~/.bashrc)"
      run dot -s $$DOT
      run dot -c $$DOT/.json
      for d in $$HOME/.dot/*; do run dot -s "$$d"; done
      [[ "$$(tail -n1 ~/.bashrc)" != "$$tail_bashrc" ]] || exit 1
      run tmux new-session -n test "vim +PlugInstall +qall; exit"
      run test -d "$$HOME/.tmux/plugins/tpm"
      run test -d "$$HOME/.vim/plugged"'
