version: "2"

services:

  golang:
    build:
      context: .
      dockerfile: docker/golang.Dockerfile # alpine
    image: lei/dot
    container_name: dot
    # entrypoint: /bin/bash
    command: -l # -c 'exec bash -l'
    environment:
      GIT_AUTHOR_NAME: Docker
      GIT_AUTHOR_EMAIL: do@ck.er

  test:
    image: lei/dot # _test
    depends_on:
      - golang
    container_name: dot_test
    command: -l -c './scripts/e2e-test.sh'

  test_os:
    build:
      context: .
      dockerfile: docker/$OS.Dockerfile
    # image: lei/dot_$OS
    container_name: dot_$OS
    command: -l -c '/tmp/scripts/e2e-test.sh'
