version: "2"

services:

  dot:
    image: lei/dot
    depends_on:
      - image
    entrypoint: /bin/bash
    command: -l -c 'dot -s $$DOT; tmux new-session "vim +PlugInstall +qall; exit"; bash -l'

  test:
    image: lei/dot
    depends_on:
      - image
    entrypoint: /bin/bash
    command: |
      -l -c '
      tail_bashrc="$$(tail -n1 ~/.bashrc)"
      # for d in $$DOT/src/*; do dot -s "$$d"; done
      dot -s $$DOT
      [[ "$$(tail -n1 ~/.bashrc)" != "$$tail_bashrc" ]] || exit 1
      tmux new-session -n test "vim +PlugInstall +qall; exit"
      test -d "$$HOME/.tmux/plugins/tpm"
      test -d "$$HOME/.vim/plugged"'

  image:
    build: .
    image: lei/dot
    container_name: dot
