version: "2"

services:

  image:
    build: .
    image: lei/dot
    container_name: dot

  debug:
    image: lei/dot
    depends_on:
      - image
    # entrypoint: /bin/bash
    command: -l -c 'run dot sync -d --https -c $$DOT/.dotrc.yml; bash --login'
    # command: -l -c 'dot -p tmux=LEI/dot-tmux -p vim=LEI/dot-vim; tmux new-session "vim +PlugInstall +qall; exit"; bash -l'

  test:
    image: lei/dot
    depends_on:
      - image
    # entrypoint: /bin/bash
    command: |
      -l -c '
      tail_bashrc="$$(tail -n1 ~/.bashrc)"
      yes | run dot sync -s $$DOT --https
      # yes | run dot sync -c $$DOT/.dotrc.yml
      # for d in $$HOME/.dot/*; do yes | run dot "$${d##*/}"; done
      [[ "$$(tail -n1 ~/.bashrc)" != "$$tail_bashrc" ]] || exit 1
      run tmux new-session -n test "vim +PlugInstall +qall; exit"
      run test -d "$$HOME/.tmux/plugins/tpm"
      run test -d "$$HOME/.vim/plugged"'
