version: "2"

services:

  dot:
    image: lei/dot
    depends_on:
      - image
    entrypoint: /bin/bash
    command: -l -c '/go/bin/dot -s $$DOT/src/tmux && tmux new-session "exit"; bash -l; cd'
    # command: -l -c '/go/bin/dot -s $$DOT/src/tmux; tmux new-session "vim +PlugInstall +qall; exit"; bash -l'

  test:
    image: lei/dot
    depends_on:
      - image
    environment:
      GIT_USER_NAME: Docker Test
      GIT_USER_USERNAME: docker
      GIT_USER_EMAIL: docker@test.io
    entrypoint: /bin/bash
    command: |
      -l -c '
      /go/bin/dot -s $$DOT/src/tmux
      tmux new-session -n test "ls -la; exit"
      /go/bin/dot -s $$DOT/src/tmux
      test -d "$$HOME/.tmux/plugins/tpm"'

  image:
    build: .
    image: lei/dot
    container_name: dot
