version: "2"

services:

  dot:
    image: lei/dot
    depends_on:
      - image
    command: -l -c 'dot -R $$DOT; tmux new-session "vim +PlugInstall +qall; exit"; bash -l'

  test:
    image: lei/dot
    depends_on:
      - image
    environment:
      GIT_USER_NAME: Docker Test
      GIT_USER_USERNAME: docker
      GIT_USER_EMAIL: docker@test.io
    command: |
      -l -c '
      bashrc=$$(tail -n1 ~/.bashrc);
      dot -R $$DOT --non-interactive;
      if [[ "$$bashrc" == "$$(tail -n1 ~/.bashrc)" ]]; then echo ~/.bashrc was not modified; exit 1; fi;
      if [[ "$$(git config --file ~/.gitconfig.local --get user.name)" != "$$GIT_USER_NAME" ]]; then echo GIT_USER_NAME not set in ~/.gitconfig.local; exit 1; fi;
      tmux new-session -n test "vim +PlugInstall +qall; exit";
      for d in $$HOME/{.tmux/plugins,.vim/plugged}; do if ! test -d $$d; then echo $$d directory is missing; exit 1; fi; done'

  image:
    build: .
    image: lei/dot
    container_name: dot
