version: "2"

services:

  dot:
    image: lei/dot
    depends_on:
      - image
    entrypoint: /bin/bash
    command: -l -c '/go/bin/dot -s $$DOT && tmux new-session "exit"; cd; /go/bin/dot -s $$DOT; bash -l'
    # command: -l -c '/go/bin/dot -s $$DOT/src/tmux; tmux new-session "vim +PlugInstall +qall; exit"; bash -l'

  test:
    image: lei/dot
    depends_on:
      - image
    entrypoint: /bin/bash
    command: |
      -l -c '
      for d in $$DOT/src/*; do /go/bin/dot -s "$$d"; done
      tmux new-session -n test "vim +PlugInstall +qall; exit"
      test -d "$$HOME/.tmux/plugins/tpm"
      /go/bin/dot -s $$DOT'

  image:
    build: .
    image: lei/dot
    container_name: dot
