version: '3'

services:

  base:
    build: .
    #   context: .
    #   dockerfile: Dockerfile
    container_name: dot
    image: lei/dot

  test:
    # command: -l # -c 'exec bash -l'
    depends_on:
      - base
    entrypoint: bin/e2e-test.sh
    # environment:
    #   GIT_AUTHOR_NAME: Docker
    #   GIT_AUTHOR_EMAIL: do@ck.er
    image: lei/dot

  test_os:
    build:
      context: .
      dockerfile: Dockerfile.$OS
    # command: -c 'bin/e2e-test.sh'
    container_name: dot_$OS
    entrypoint: bin/e2e-test.sh
    environment:
      - DOT=$GOPATH/github.com/LEI/dot
    # image: LEI/dot-$OD
