version: "2"

services:

  dotimg:
    build: .
    image: lei/dot
    container_name: dot
    # entrypoint: /bin/bash
    environment:
      GIT_AUTHOR_NAME: Docker
      GIT_AUTHOR_EMAIL: do@ck.er
    command: |
      -l -c '
      # run dot --https;
      # run tmux -2 -u new-session -n test "vim -E -s -u $$HOME/.vimrc +PlugInstall +qall; exit";
      exec bash -l;'
    # command: -l -c 'dot -p tmux=LEI/dot-tmux -p vim=LEI/dot-vim; tmux new-session "vim +PlugInstall +qall; exit"; bash -l'

  test:
    image: lei/dot
    depends_on:
      - dotimg
    container_name: dot_test
    # entrypoint: /bin/bash
    command: |
      -l -c '
      touch ~/.dot/git;
      touch ~/.gitconfig;
      touch ~/.gitconfig.local;
      dot clone -u "https://github.com/LEI/dot-git" -d "$$HOME/.dot/git";
      dot clone -u "https://github.com/LEI/dot-tmux" -d "$$HOME/.dot/tmux";
      dot clone -u "https://github.com/LEI/dot-vim" -d "$$HOME/.dot/vim";
      dot link -d "$$HOME/.dot/git" \
        ".gitconfig:$$HOME" \
        ".gitignore:$$HOME";
      dot template -d "$$HOME/.dot/git" \
        ".gitconfig.local.tpl:$$HOME";
      dot link -d "$$HOME/.dot/tmux" \
        "tmux.conf:$$HOME/.tmux" \
        "tmux-*.conf:$$HOME/.tmux" \
        "tmux.\$$OS.conf:$$HOME/.tmux" \
        "colors:$$HOME/.tmux";
      dot link -d "$$HOME/.dot/vim" \
        "autoload/*:$$HOME/.vim/autoload" \
        "*.vim:$$HOME/.vim" \
        "config:$$HOME/.vim" \
        "ftdetect:$$HOME/.vim" \
        "ftplugin:$$HOME/.vim" \
        "plugin:$$HOME/.vim";
        #"[^.]*[^\.md]?:$$HOME/.vim"
      ls -la ~
      cat ~/.git*
      # tail_bashrc="$$(tail -n1 ~/.bashrc)"
      # yes | run dot -s $$DOT --https
      # run tmux -2 -u new-session -n test "vim -E -s -u $$HOME/.vimrc +PlugInstall +qall; exit"
      # for f in "$$HOME"/.gitconfig; do run test -f "$$f"; done
      # for d in "$$HOME"/{.tmux/plugins/tpm,.vim/plugged}; do run test -d "$$d"; done
      # [[ "$$(tail -n1 ~/.bashrc)" != "$$tail_bashrc" ]] || exit 1
      # yes | run dot remove -c $$DOT/.dotrc.yml
      # yes | run dot rm --https --empty;
      # [[ "$$(tail -n1 ~/.bashrc)" == "$$tail_bashrc" ]] || exit 1
      # touch ~/{.bashrc,.vim/init.vim}
      # yes | run dot install -d -f bash,vim -c $$DOT/.dotrc.yml
      # # for d in $$HOME/.dot/*; do yes | run dot "$${d##*/}"; done'
