version: "2"

services:

  dotimg:
    build: .
    image: lei/dot
    container_name: dot
    # entrypoint: /bin/bash
    environment:
      GIT_AUTHOR_NAME: Docker
      GIT_AUTHOR_EMAIL: do@ck.er
    command: -l -c 'run dot --https; run dot rm --empty -f vim; exec bash -l'
      # run tmux new-session -n test "vim -E -s -u $$HOME/.vim/vimrc +PlugInstall +qall; exit";
      # bash --login'
    # command: -l -c 'dot -p tmux=LEI/dot-tmux -p vim=LEI/dot-vim; tmux new-session "vim +PlugInstall +qall; exit"; bash -l'

  test:
    image: lei/dot
    depends_on:
      - dotimg
    # entrypoint: /bin/bash
    command: |
      -l -c '
      tail_bashrc="$$(tail -n1 ~/.bashrc)"
      yes | run dot -s $$DOT --https
      run tmux new-session -n test "vim -E -s -u $$HOME/.vim/vimrc +PlugInstall +qall; exit"
      for f in "$$HOME"/.gitconfig; do run test -f "$$f"; done
      for d in "$$HOME"/{.tmux/plugins/tpm,.vim/plugged}; do run test -d "$$d"; done
      [[ "$$(tail -n1 ~/.bashrc)" != "$$tail_bashrc" ]] || exit 1
      yes | run dot remove -c $$DOT/.dotrc.yml
      yes | run dot rm --https --empty;
      [[ "$$(tail -n1 ~/.bashrc)" == "$$tail_bashrc" ]] || exit 1
      touch ~/{.bashrc,.vim/init.vim}
      yes | run dot install -d -f bash,vim -c $$DOT/.dotrc.yml
      # for d in $$HOME/.dot/*; do yes | run dot "$${d##*/}"; done'
